### ISSUE TITLE
GitHub courses to be completed

### ISSUE THREAD

**Issue by brucehoward-cl** [brucehoward-cl/medals#2]
## TODO

*Courses to be completed:

* [] Working By Yourself
* [] Working on a Team
* [] Create a Web Presence
* [] Get Involved in OpenSource

:tada:
